PFCAssignment/PFCAssignment/Controllers/CarCategoryPricingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PFCAssignment.DataAccess.Interfaces;
using PFCAssignment.Models;
using PFCAssignment.Utilities.Interfaces;

namespace PFCAssignment.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CarCategoryPricingController : Controller
    {
        private readonly ICarCatCacheRepository _repo;
        private readonly ILogHandler _log;

        public CarCategoryPricingController(ICarCatCacheRepository repo, ILogHandler log)
        {
            _repo = repo;
            _log = log;
        }

        public IActionResult Index()
        {
            try
            {
                if (TempData["error"] != string.Empty)
                {
                    ViewBag.Error = TempData["error"];
                }

                if (TempData["message"] != string.Empty)
                {
                    ViewBag.Message = TempData["message"];
                }

                return View(_repo.GetPrices());
            }
            catch
            {
                _log.Log("Error occured when attempting to retreive prices from cache.", 
                    Google.Cloud.Logging.Type.LogSeverity.Error);

                ViewBag.Error = "Error occured when attempting to load " +
                    "prices ";
                return View();
            }
        }

        public IActionResult UpdatePrice()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdatePrice(CarCategoryResponse carCategoryResponse)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("Model was not valid");

                _repo.UpdatePrice(carCategoryResponse);


                TempData["message"] = $"Successfully updated price of {carCategoryResponse.CarCategoryType.ToString().ToLower()} category";

                _log.Log($"User {User.Identity.Name} has updated the price of category {carCategoryResponse.CarCategoryType}.",
                    Google.Cloud.Logging.Type.LogSeverity.Info);

                return RedirectToAction("Index");
            }
            catch
            {
                _log.Log($"Error occured when attempting to update the price for category {carCategoryResponse.CarCategoryType}.",
                    Google.Cloud.Logging.Type.LogSeverity.Error);

                TempData["error"] = "Error occured when attempting to update the prices " +
                    $"for a category.";
            }

            return View();
        }
    }
}

PFCAssignment/PFCAssignment/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Google.Cloud.Storage.V1;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using PFCAssignment.DataAccess.Interfaces;
using PFCAssignment.Domain;
using PFCAssignment.Utilities.Interfaces;

namespace PFCAssignment.Controllers
{
    [Authorize(Roles = "Driver")]
    public class CarsController : Controller
    {
        private readonly ICarsRepository _repo;
        private readonly IConfiguration _config;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ILogHandler _log;

        public CarsController(ICarsRepository repo, IConfiguration config,
            UserManager<IdentityUser> userManager, ILogHandler log)
        {
            _repo = repo;
            _config = config;
            _userManager = userManager;
            _log = log;
        }

        public ActionResult Details()
        {
            try
            {
                if (TempData["error"] != string.Empty)
                {
                    ViewBag.Error = TempData["error"];
                }

                if (TempData["message"] != string.Empty)
                {
                    ViewBag.Message = TempData["message"];
                }

                var userName = User.Identity.Name;

                return View(_repo.GetCar(userName));
            }
            catch
            {
                string message = "Error occured  when attempting " +
                    "to load driver's cars from db";
                _log.Log(message, Google.Cloud.Logging.Type.LogSeverity.Error);

                ViewBag.Error = message;

                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                string bucketName = _config.GetSection("AppSettings").GetSection("PhotosBucket").Value;
                string stringToReplace = $"https://storage.googleapis.com/{bucketName}/";
                var carPhoto = _repo.GetCar(id).Photo;
                string filename = carPhoto.Replace(stringToReplace,"");

                _repo.Delete(id);

                var storage = StorageClient.Create();
                storage.DeleteObject(bucketName, filename, null);

                TempData["messsage"] = "Car was successfully deleted";
                _log.Log($"Car with previous id {id} and its respective image " +
                    "were deleted", Google.Cloud.Logging.Type.LogSeverity.Info);

            }
            catch
            {
                string message = "Error occured when attempting to delete car";
                _log.Log(message, Google.Cloud.Logging.Type.LogSeverity.Error);

                TempData["error"] = message;
            }
            return RedirectToAction(nameof(Details));
        }

        public ActionResult Create()
        {
            return View();
        }

        // TODO: Test
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormFile carPhoto, Car newCar)
        {
            try
            {
                string bucketName = _config.GetSection("AppSettings").GetSection("PhotosBucket").Value;

                string filename = Guid.NewGuid() + Path.GetExtension(carPhoto.FileName);

                newCar.Photo = $"https://storage.googleapis.com/{bucketName}/{filename}";

                var storage = StorageClient.Create();
                using (var fileToUpload = carPhoto.OpenReadStream())
                {
                    storage.UploadObject(bucketName, filename, null, fileToUpload);
                }

                var driver = _userManager.GetUserAsync(User).Result;
                newCar.Driver = driver;
                newCar.DriverId = driver.Id;

                if (!ModelState.IsValid)
                    throw new ArgumentException();

                _repo.AddCar(newCar);

                TempData["message"] = "Car was successfully registered";

                return RedirectToAction(nameof(Details));
            }
            catch
            {
                string message = "An error occured when attempting to register " +
                    "a new car";
                _log.Log(message, Google.Cloud.Logging.Type.LogSeverity.Error);

                ViewBag.Error = message;

                return View();
            }
        }
    }
}

PFCAssignment/PFCAssignment/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PFCAssignment.Utilities.Interfaces;

namespace PFCAssignment.Controllers
{
    public class RolesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ILogHandler _log;

        public RolesController(UserManager<IdentityUser> userManager, 
            RoleManager<IdentityRole> roleManager, ILogHandler log)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _log = log;
        }

        public IActionResult ListRoles()
        {
            try
            {
                if (TempData["error"] != string.Empty)
                {
                    ViewBag.Error = TempData["error"];
                }

                if (TempData["message"] != string.Empty)
                {
                    ViewBag.Message = TempData["message"];
                }

                var roles = _roleManager.Roles.ToList();
                return View(roles);
            }
            catch
            {
                _log.Log("Error occured when attempting to retreive roles.",
                    Google.Cloud.Logging.Type.LogSeverity.Error);

                return View(new List<IdentityRole>() { });   
            }
        }

        public IActionResult Create()
        {
            return View(new IdentityRole());
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            try
            {
                await _roleManager.CreateAsync(role);

                _log.Log($"New role was created {role.Name}",
                   Google.Cloud.Logging.Type.LogSeverity.Info);
            }
            catch
            {
                _log.Log("Error occured when attempting to retreive roles.",
                   Google.Cloud.Logging.Type.LogSeverity.Error);

                TempData["error"] = "Error occured when attempting to create " +
                    "a new role";
            }

            return RedirectToAction("ListRoles");
        }

        public IActionResult UpdateUserRole()
        {
            ViewBag.Roles = _roleManager.Roles.Select(r => r.Name).ToList().Select(
               f => new SelectListItem { Text = f, Value = f });
            ViewBag.Users = _userManager.Users.Select(u => u.UserName).ToList().Select(
               f => new SelectListItem { Text = f, Value = f });

            return View();
        }

        [HttpPost]
        public IActionResult UpdateUserRole(string userName, string role)
        {
            try
            {
                var user = _userManager.FindByNameAsync(userName).Result;
                var currentRole = _userManager.GetRolesAsync(user).Result.First();

                var removal_result = _userManager.RemoveFromRoleAsync(user, currentRole).Result;

                if (removal_result.Succeeded)
                {
                    var insertion_result = _userManager.AddToRoleAsync(user, role).Result;

                    if (!insertion_result.Succeeded)
                        throw new Exception("Insertion of new role not successful");
                }
                else
                {

                    throw new Exception("Error occured when attempting to remove role");
                }

                TempData["message"] = "User Role Successfully updated";

                _log.Log($"Updated user {userName} to role {role}", Google.Cloud.Logging.Type.LogSeverity.Info);

                return RedirectToAction("ListRoles");
            }
            catch
            {

                string message = $"Error occured when attempting to update role of user {userName} to {role}";
                _log.Log(message, Google.Cloud.Logging.Type.LogSeverity.Error);

                TempData["error"] = message;

                return RedirectToAction("ListRoles");
            }
        }
    }
}

PFCAssignment/PFCAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PFCAssignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (User.IsInRole("Passenger"))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Bookings" asp-action="Create">PFCAssignment</a>
                }

                @if (User.IsInRole("Driver"))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Bookings" asp-action="GetAvailableJobs">PFCAssignment</a>
                }

                @if (User.IsInRole("Admin"))
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Bookings" asp-action="GetAcknowledgedBookings">PFCAssignment</a>
                }

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.IsInRole("Admin"))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="GetAcknowledgedBookings">Bookings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="ListRoles">Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CarCategoryPricing" asp-action="Index">Pricing</a>
                            </li>
                        }

                        @if (User.IsInRole("Driver"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="GetAvailableJobs">Bookings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Details">Car</a>
                            </li>
                        }

                        @if (User.IsInRole("Passenger"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Create">Create Booking</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PFCAssignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>