PFCAssignment/PFCAssignment/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using DinkToPdf.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PFCAssignment.DataAccess.Interfaces;
using PFCAssignment.Domain;
using PFCAssignment.Models;
using PFCAssignment.Utilities.Implementations;
using PFCAssignment.Utilities.Interfaces;

namespace PFCAssignment.Controllers
{
    public class BookingsController : Controller
    {
        private readonly IBookingsRepository _repo;
        private readonly ICarsRepository _carRepo;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IPubSubRepository _pubSubRepository;
        private readonly ILogHandler _log;
        private readonly ICarCatCacheRepository _cacheRepo;
        private readonly ICacheHandler _cacheHandler;

        public BookingsController(IBookingsRepository repo,
            UserManager<IdentityUser> userManager, ICarsRepository carRepo,
            IPubSubRepository pubSubRepository,
            ILogHandler log,
            ICarCatCacheRepository cacheRepo,
            ICacheHandler cacheHandler)
        {
            _repo = repo;
            _userManager = userManager;
            _carRepo = carRepo;
            _pubSubRepository = pubSubRepository;
            _log = log;
            _cacheRepo = cacheRepo;
            _cacheHandler = cacheHandler;
        }

        /// <summary>
        /// Returns acknowledged bookings from database. Operation is available
        /// only for admins
        /// </summary>
        [Authorize(Roles = "Admin")]
        public ActionResult GetAcknowledgedBookings()
        {
            try
            {

                var displayData = _repo.GetAcknowledgedBookings();

                string message = $"User {User.Identity.Name}" +
                    $" requested all acknowledged bookings from the database.";

                _log.Log(message, Google.Cloud.Logging.Type.LogSeverity.Info);

                return View(displayData);
            }
            catch
            {
                string message = "Error occured when admin attempted to retreive acknowledged" +
                    $"bookings from db. ";
                _log.Log(message, Google.Cloud.Logging.Type.LogSeverity.Error);

                TempData["error"] = "Error occured when attempting to get acknowledged bookings";
                return View(new List<Booking>());
            }
        }

        /// <summary>
        /// Loads the first available job from the respective car topic
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Driver")]
        public ActionResult GetAvailableJobs()
        {
            try
            {
                if (TempData["error"] != string.Empty)
                {
                    ViewBag.Error = TempData["error"];
                }

                if (TempData["message"] != string.Empty)
                {
                    ViewBag.Message = TempData["message"];
                }

                //select from which topic to request from
                string carCategory = _carRepo.GetCar(User.Identity.Name)?.CarCategory.ToString();

                // load first message from respective topic
                var firstMessageResponse = _pubSubRepository.GetFirstMessage(carCategory);
                string firstMessage = firstMessageResponse.Item1;

                CreateBookingRequest output = JsonConvert.DeserializeObject<CreateBookingRequest>(firstMessage);

                if (output == null)
                {
                    ViewBag.Message = "No available jobs were found";
                    _log.Log($"No bookings were loaded from the topic {carCategory}",
                        Google.Cloud.Logging.Type.LogSeverity.Info);
                }


                if (output != null)
                {
                    ViewBag.AckIds = JsonConvert.SerializeObject(firstMessageResponse.Item2);
                    ViewBag.Request = JsonConvert.SerializeObject(output);
                }


                string message = $"User {User.Identity.Name}" +
                   $" requested the first available booking in the pubsub.";

                _log.Log(message, Google.Cloud.Logging.Type.LogSeverity.Info);

                return View(output);
            }
            catch
            {
                _log.Log("Error occured when admin attempted to retreive first" +
                   $"available job from pub sub.", Google.Cloud.Logging.Type.LogSeverity.Error);

                TempData["error"] = "Error occured when attempting to get available jobs";
                return View(new List<Booking>());
            }
        }

        /// <summary>
        /// Sets the supplied booking to acknowledge, downloads the details and redirects to the 
        /// available jobs page
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Driver")]
        public ActionResult Acknowledge(string createBookingRequestStr, string ackIds)
        {
            try
            {
                CreateBookingRequest createBookingRequest = JsonConvert.DeserializeObject<CreateBookingRequest>
                    (createBookingRequestStr);

                var driver = _userManager.GetUserAsync(User).Result;
                Car assignedCar = _carRepo.GetCar(User.Identity.Name);

                // acknowledge in pubsub
                _pubSubRepository.Acknowledge(assignedCar.CarCategory.ToString(), ackIds);

                string message = $"User {User.Identity.Name}" +
                    $" acknowledged a booking.";

                _log.Log(message, Google.Cloud.Logging.Type.LogSeverity.Info);

                //prep data for saving in db
                Booking booking = new Booking()
                {
                    PickUpAddress = createBookingRequest.PickUpAddress,
                    DropOffAddress = createBookingRequest.DropOffAddress,
                    PassengerId = createBookingRequest.Passenger.Id,
                    CarTypeRequested = createBookingRequest.CarType,
                    Acknowledged = true,
                    DriverId = driver.Id,
                    AssignedCar = assignedCar,
                    AssignedCarId = assignedCar.CarId
                };

                int bookingId = _repo.AddBooking(booking);

                if (bookingId == 0)
                {
                    throw new ApplicationException("Booking Id was left as 0. Could indicate" +
                        " that the booking was not inserted correctly");
                }

                _log.Log("Successfully inserted a new booking into the database.",
                    Google.Cloud.Logging.Type.LogSeverity.Info);


                //Adding entry to the cache so that cron job can send the email
                _cacheHandler.AddEntryToBookingCachedData(new KeyValuePair<int, CreateBookingRequest>(bookingId, createBookingRequest));

                //generating downloadable details
                dynamic downloadableDetails = new ExpandoObject();
                downloadableDetails.BookingId = bookingId;
                downloadableDetails.PickUpAddress = createBookingRequest.PickUpAddress;
                downloadableDetails.DropOffAddress = createBookingRequest.DropOffAddress;
                downloadableDetails.PassengerName = createBookingRequest.Passenger.UserName;

                var fileToDownload = Encoding.ASCII.GetBytes(
                    JsonConvert.SerializeObject(downloadableDetails));

                return File(fileToDownload, "text/plain", $"Booking{bookingId}Details.txt");
            }
            catch
            {
                _log.Log("Error occured when admin attempted to acknowledge booking from" +
                 $"pubsub or when downloading details.", Google.Cloud.Logging.Type.LogSeverity.Error);

                TempData["error"] = "Error occured when attempting to acknowledge " +
                    "booking";

                return RedirectToAction("GetAvailableJobs");
            }
        }

        [Authorize(Roles = "Passenger")]
        public ActionResult ConfirmBooking(CreateBookingRequest createBookingRequest)
        {
            return View(createBookingRequest);
        }


        [Authorize(Roles = "Passenger")]
        public ActionResult Create()
        {
            if (TempData["error"] != string.Empty)
            {
                ViewBag.Error = TempData["error"];
            }

            if (TempData["message"] != string.Empty)
            {
                ViewBag.Message = TempData["message"];
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Passenger")]
        public ActionResult Create(CreateBookingRequest createBookingRequest)
        {
            try
            {
                createBookingRequest.Passenger = _userManager.GetUserAsync(User).Result;
                createBookingRequest.TripPrice = _cacheRepo.GetPriceForCategory(createBookingRequest.CarType);

                TempData["request"] = JsonConvert.SerializeObject(createBookingRequest);
            }
            catch
            {
                _log.Log($"Error occured when user {User.Identity.Name} attempted to create a " +
                    $"new booking.",
                  Google.Cloud.Logging.Type.LogSeverity.Error);

                ViewBag.Error = "Error occured when attempting to create a new booking.";
            }

            return RedirectToAction("ConfirmBooking", createBookingRequest);
        }

        [Authorize(Roles = "Passenger")]
        public ActionResult InsertBooking()
        {
            try
            {

PFCAssignment/PFCAssignment/Views/Bookings/ConfirmBooking.cshtml
@model PFCAssignment.Models.CreateBookingRequest

@{
    ViewData["Title"] = "Details";
}

<h1>Create Booking</h1>

<div>
    <h4>Confirm Details</h4>
    <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PickUpAddress)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PickUpAddress)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DropOffAddress)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DropOffAddress)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CarType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CarType)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TripPrice)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TripPrice)
            </dd>
        </dl>
    <hr/>
        <div class="row">
            <div class="col-2">
                @Html.ActionLink("Create Booking", "InsertBooking", "Bookings", null, new { @class = "btn btn-danger" })
            </div>
            <div class="col-2">
                @Html.ActionLink("Change Details", "Create", "Bookings", null, new { @class = "btn btn-primary" })
            </div>
        </div>
</div>

PFCAssignment/PFCAssignment/Views/Bookings/Create.cshtml
@model PFCAssignment.Models.CreateBookingRequest

@{
    ViewData["Title"] = "Create";
}

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Error
    </div>
}

<h1>Create</h1>

<h4>Booking</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Pick Up Address</label>
                <input asp-for="PickUpAddress" class="form-control" />
                <span asp-validation-for="PickUpAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Drop Off Address</label>
                <input asp-for="DropOffAddress" class="form-control" />
                <span asp-validation-for="DropOffAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Car Type</label>
                <select asp-for="CarType" asp-items="Html.GetEnumSelectList<CarCategory>()" class="form-control">
                    <option selected="selected" value="">Please select</option>
                </select>
                <span asp-validation-for="CarType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Next" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PFCAssignment/PFCAssignment/Views/Bookings/GetAcknowledgedBookings.cshtml
@model IEnumerable<PFCAssignment.Domain.Booking>

@{
    ViewData["Title"] = "Acknowledged Bookings";
}

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Error
    </div>
}

<h1>Confirmed Bookings</h1>
<hr />

@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PickUpAddress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DropOffAddress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Acknowledged)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AssignedCarId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PassengerId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DriverId)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PickUpAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DropOffAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Acknowledged)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AssignedCarId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PassengerId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DriverId)
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-info" role="alertdialog">
        There are currently no acknowledged bookings
    </div>
}

PFCAssignment/PFCAssignment/Views/Bookings/GetAvailableJobs.cshtml
@model PFCAssignment.Models.CreateBookingRequest

@{
    ViewData["Title"] = "GetAvailableJobs";
}

<META HTTP-EQUIV="refresh" content="15" />

<h1>Available Job</h1>

<hr />

@if (ViewBag.Message != null)
{
    <div class="alert alert-info" role="alert">
        @ViewBag.Message
    </div>
}

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Error
    </div>
}

@if (Model != null)
{
    <div>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PickUpAddress)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => modelItem.PickUpAddress)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.DropOffAddress)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => modelItem.DropOffAddress)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CarType)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => modelItem.CarType)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Passenger.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(modelItem => modelItem.Passenger.Email)
            </dd>
        </dl>
    </div>

    <div>
        @Html.ActionLink(
        linkText: "Acknowledge",
        actionName: "Acknowledge",
        controllerName: "Bookings",
        routeValues: new
        {
            createBookingRequestStr = ViewBag.Request,
            ackIds = ViewBag.AckIds
        },
        htmlAttributes: new { @class = "btn  btn-primary" }
    )
    </div>
}